{% set name = "pyspark-flame" %}
{% set version = "0.2.9" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9b0ccb3e6a56bd433e6330f26ba60746b49e4505c1d934b9ec73a1f7c5f1c4a

build:
  noarch: python
  number: 2
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pypandoc
    - python {{ python_min }}
    - setuptools
  run:
    - pyspark >=3.0.0
    - python >={{ python_min }}

test:
  imports:
    - pyspark_flame
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/jamespic/pyspark-flame
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: A low-overhead sampling profiler for PySpark, that outputs Flame Graphs

extra:
  recipe-maintainers:
    - benjamb
    - nowster
